"""add settings

Revision ID: c9cb0c5cc85e
Revises: 5ed489d1682d
Create Date: 2026-05-10 23:08:01.898294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cb0c5cc85e'
down_revision: Union[str, None] = '5ed489d1682d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_messages', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('friendship_test_results', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('poll_answers', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_muted_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('risk_score', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('allow_anonymous_messages', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('allow_friend_requests', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('allow_polls', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('show_risk_status', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_risk_status')
    op.drop_column('users', 'allow_polls')
    op.drop_column('users', 'allow_friend_requests')
    op.drop_column('users', 'allow_anonymous_messages')
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'is_muted_until')
    op.drop_column('poll_answers', 'is_read')
    op.drop_column('friendship_test_results', 'is_read')
    op.drop_column('anonymous_messages', 'is_read')
    # ### end Alembic commands ###
